#!/usr/bin/env bash
#
# env file から対象環境の Terraform backend と変数の設定ファイルを生成する。
#
# Requirement Bash Version
#   GNU Bash 4.4 or later
#
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
readonly SCRIPT_DIR
INFRA_DIR="$(cd -- "${SCRIPT_DIR}/../.." >/dev/null 2>&1 && pwd -P)"
readonly INFRA_DIR
GENERATED_FILE_HEADER="# Generated by bootstrap/scripts/configure-terraform.sh. Do not edit."
readonly GENERATED_FILE_HEADER
LEGACY_BACKEND_FILE_HEADER="# Generated by bootstrap/scripts/configure-backend.sh. Do not edit."
readonly LEGACY_BACKEND_FILE_HEADER

# shellcheck source-path=SCRIPTDIR
# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"

# 使用方法を表示する。
usage() {
	cat <<'USAGE'
Usage:
  configure-terraform.sh --env-file ENV_FILE

Required option:
  --env-file ENV_FILE  Project IDs, locations, ENVIRONMENT, and SUFFIX input file

Other option:
  -h, --help            Show this help

Example:
  ./bootstrap/scripts/configure-terraform.sh --env-file config/dev.env.local

Exit status:
  0  Terraform configuration completed
  1  Authentication or Google Cloud operation failed
  2  Invalid command-line option or input
USAGE
}

# 生成した一時ファイルを管理対象の設定ファイルとして配置する。
install_generated_file() {
	local temporary_file="$1"
	local target_file="$2"
	local description="$3"
	local first_line=""

	if [[ -f "${target_file}" ]]; then
		IFS= read -r first_line <"${target_file}" || true
		if [[ "${first_line}" != "${GENERATED_FILE_HEADER}" &&
			"${first_line}" != "${LEGACY_BACKEND_FILE_HEADER}" ]]; then
			rm -f -- "${temporary_file}"
			die "Refusing to overwrite an unmanaged file: ${target_file}"
		fi
	fi

	if [[ -f "${target_file}" ]] && cmp -s -- "${temporary_file}" "${target_file}"; then
		rm -f -- "${temporary_file}"
		log success "${description}: already current"
		return 0
	fi

	# Git管理外の生成ファイルを同一filesystem内で置き換える。
	if ! chmod 0644 "${temporary_file}"; then
		rm -f -- "${temporary_file}"
		die "Failed to set generated file permissions: ${target_file}"
	fi
	if ! mv -f -- "${temporary_file}" "${target_file}"; then
		rm -f -- "${temporary_file}"
		die "Failed to install generated file: ${target_file}"
	fi
	log success "${description}: written to ${target_file}"
}

# 対象環境のGCS backend設定ファイルを生成する。
write_backend_configuration() {
	local terraform_root="$1"
	local backend_file="${terraform_root}/terraform-backend.tf"
	local temporary_file

	temporary_file="$(mktemp "${terraform_root}/.terraform-backend.tf.XXXXXX")" \
		|| die "Failed to create a temporary backend file."

	if ! printf '%s\n' \
		"${GENERATED_FILE_HEADER}" \
		'terraform {' \
		'  backend "gcs" {' \
		"    bucket = \"${BUCKET_NAME}\"" \
		"    prefix = \"${BACKEND_PREFIX}\"" \
		'  }' \
		'}' >"${temporary_file}"; then
		rm -f -- "${temporary_file}"
		die "Failed to write the Terraform backend configuration."
	fi

	install_generated_file "${temporary_file}" "${backend_file}" "Terraform backend"
}

# 対象環境のTerraform変数ファイルを生成する。
write_variable_values() {
	local terraform_root="$1"
	local variable_file="${terraform_root}/terraform.auto.tfvars"
	local temporary_file

	temporary_file="$(mktemp "${terraform_root}/.terraform.auto.tfvars.XXXXXX")" \
		|| die "Failed to create a temporary variable file."

	if ! printf '%s\n' \
		"${GENERATED_FILE_HEADER}" \
		"project_id_raw_data  = \"${PROJECT_ID_RAW_DATA}\"" \
		"project_id_mart_red  = \"${PROJECT_ID_MART_RED}\"" \
		"project_id_mart_blue = \"${PROJECT_ID_MART_BLUE}\"" \
		"location_raw_data    = \"${LOCATION_RAW_DATA,,}\"" \
		"location_mart_red    = \"${LOCATION_MART_RED,,}\"" \
		"location_mart_blue   = \"${LOCATION_MART_BLUE,,}\"" \
		"environment          = \"${ENVIRONMENT}\"" \
		"suffix               = \"${SUFFIX}\"" >"${temporary_file}"; then
		rm -f -- "${temporary_file}"
		die "Failed to write the Terraform variable values."
	fi

	install_generated_file "${temporary_file}" "${variable_file}" "Terraform variables"
}

main() {
	local terraform_root

	parse_common_args "configure-terraform" "$@"
	if [[ "${HELP_REQUESTED}" == "true" ]]; then
		usage
		return 0
	fi

	load_env_file
	validate_inputs
	derive_values
	verify_tool_versions
	verify_authentication_and_project
	print_execution_context

	terraform_root="${INFRA_DIR}/terraform/environments/${ENVIRONMENT}"
	[[ -d "${terraform_root}" ]] || die "Terraform root was not found: ${terraform_root}"

	if ! has_state_bucket; then
		die "State bucket was not found in project ${PROJECT_ID_RAW_DATA}: ${BUCKET_URL}"
	fi
	verify_bucket_configuration || die "State bucket configuration does not match bootstrap."

	log warning "Terraform root: ${terraform_root}"
	log warning "Configuring GCS backend: ${BUCKET_NAME}/${BACKEND_PREFIX}"
	write_backend_configuration "${terraform_root}"
	write_variable_values "${terraform_root}"
	log success "Result: Terraform configuration completed"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
	main "$@"
fi
