#!/usr/bin/env bash
#
# env ファイルから対象環境の Terraform backend と tfvars ファイルを生成する。
#
# Requirement Bash Version
#   GNU Bash 4.4 or later
#
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
readonly SCRIPT_DIR
PROJECT_ROOT_DIR="$(cd -- "${SCRIPT_DIR}/../.." >/dev/null 2>&1 && pwd -P)"
readonly PROJECT_ROOT_DIR

readonly -a DEPLOYMENTS=("raw_data" "mart_red" "mart_blue")
readonly GENERATED_FILE_HEADER="# Generated by scripts/terraform-configure.sh. Do not edit."

# shellcheck source-path=SCRIPTDIR
# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"

# 使用方法を表示する。
usage() {
	cat <<'USAGE'
Usage:
  terraform-configure.sh --env-file ENV_FILE

Required option:
  --env-file ENV_FILE  Project IDs, locations, ENVIRONMENT, and SUFFIX input file

Other option:
  -h, --help            Show this help

Example:
  ./scripts/terraform-configure.sh --env-file config/dev.env.local

Exit status:
  0  Terraform configuration completed
  1  Authentication or Google Cloud operation failed
  2  Invalid command-line option or input
USAGE
}

# 指定した一時ファイルを実際の管理対象ファイルとして配置する。
move_generated_file() {
	local temporary_file="$1"
	local target_file="$2"
	local description="$3"

	# 既存ファイルが同一ファイルであった場合スキップ。
	if [[ -f "${target_file}" ]] && cmp -s -- "${temporary_file}" "${target_file}"; then
		rm -f -- "${temporary_file}"
		log success "${description}: already current"
		return 0
	fi

	# mktemp で作成されている一時ファイルのパーミッションを変更する。
	if ! chmod 0644 "${temporary_file}"; then
		rm -f -- "${temporary_file}"
		die "Failed to set generated file permissions: ${target_file}"
	fi

	# 一時ファイルを実際のファイルパスに移動する。
	if ! mv -f -- "${temporary_file}" "${target_file}"; then
		rm -f -- "${temporary_file}"
		die "Failed to move generated file: ${target_file}"
	fi
	log success "${description}: written to ${target_file}"
}

# Terraform Backend ファイルを生成する。
write_backend_configuration() {
	local terraform_backend_file="$1"
	local backend_prefix="$2"
	local temporary_file

	temporary_file="$(mktemp "${terraform_backend_file}.XXXXXX")" \
		|| die "Failed to create a temporary backend file."

	if ! printf '%s\n' \
		"${GENERATED_FILE_HEADER}" \
		'terraform {' \
		'  backend "gcs" {' \
		"    bucket = \"${BUCKET_NAME}\"" \
		"    prefix = \"${backend_prefix}\"" \
		'  }' \
		'}' >"${temporary_file}"; then
		rm -f -- "${temporary_file}"
		die "Failed to write the Terraform backend configuration."
	fi

	move_generated_file "${temporary_file}" "${terraform_backend_file}" "Terraform backend"
}

# Terraform tfvars ファイルを生成する。
write_variable_values() {
	local terraform_variables_file="$1"
	local terraform_project_id="$2"
	local terraform_location="$3"
	local deployment="$4"
	local temporary_file

	temporary_file="$(mktemp "${terraform_variables_file}.XXXXXX")" \
		|| die "Failed to create a temporary variable file."

    # 共通
	if ! printf '%s\n' \
		"${GENERATED_FILE_HEADER}" \
		"project_id  = \"${terraform_project_id}\"" \
		"location    = \"${terraform_location,,}\"" \
		"environment = \"${ENVIRONMENT}\"" \
		"suffix      = \"${SUFFIX}\"" >"${temporary_file}"; then
		rm -f -- "${temporary_file}"
		die "Failed to write the Terraform variable values."
	fi

	# staging dataset を参照する、各 mart の dataform サービスアカウント
	if [[ "${deployment}" == "raw_data" ]]; then
		if ! printf '%s\n' \
			"mart_red_runtime_service_account_email = \"dataform-runtime-${ENVIRONMENT}@${PROJECT_ID_MART_RED}.iam.gserviceaccount.com\"" \
			"mart_blue_runtime_service_account_email = \"dataform-runtime-${ENVIRONMENT}@${PROJECT_ID_MART_BLUE}.iam.gserviceaccount.com\"" >>"${temporary_file}"; then
			rm -f -- "${temporary_file}"
			die "Failed to write the Mart runtime configuration."
		fi
	fi

	# 各 mart が参照する staging dataset
	if [[ "${deployment}" == "mart_red" || "${deployment}" == "mart_blue" ]]; then
		if ! printf '%s\n' \
			"raw_data_project_id = \"${PROJECT_ID_RAW_DATA}\"" \
			"raw_data_staging_dataset_id = \"stg_sakila_${SUFFIX//-/_}_${ENVIRONMENT//-/_}\"" >>"${temporary_file}"; then
			rm -f -- "${temporary_file}"
			die "Failed to write the ${deployment} staging configuration."
		fi
	fi

	move_generated_file "${temporary_file}" "${terraform_variables_file}" "Terraform variables"
}

# 全 deployment の Terraform root が存在することを確認する。
verify_terraform_roots() {
	local deployment
	local terraform_root_dir

	for deployment in "${DEPLOYMENTS[@]}"; do
		terraform_root_dir="${PROJECT_ROOT_DIR}/terraform/deployments/${deployment}/${ENVIRONMENT}"
		[[ -d "${terraform_root_dir}" ]] \
			|| die "Terraform root was not found: ${terraform_root_dir}"
	done
}

# deployment ごとに Terraform backend と tfvars ファイルを生成する。
configure_deployment() {
	local deployment="$1"
	local terraform_root_dir
	local terraform_backend_file
	local terraform_variables_file
	local terraform_project_id
	local terraform_location
	local backend_prefix

	case "${deployment}" in
		raw_data)
			terraform_project_id="${PROJECT_ID_RAW_DATA}"
			terraform_location="${LOCATION_RAW_DATA}"
			;;
		mart_red)
			terraform_project_id="${PROJECT_ID_MART_RED}"
			terraform_location="${LOCATION_MART_RED}"
			;;
		mart_blue)
			terraform_project_id="${PROJECT_ID_MART_BLUE}"
			terraform_location="${LOCATION_MART_BLUE}"
			;;
		*)
			die "Unsupported deployment: ${deployment}" 2
			;;
	esac

	terraform_root_dir="${PROJECT_ROOT_DIR}/terraform/deployments/${deployment}/${ENVIRONMENT}"
	terraform_backend_file="${terraform_root_dir}/terraform-backend.tf"
	terraform_variables_file="${terraform_root_dir}/terraform.auto.tfvars"
	backend_prefix="data_infra/${deployment}/${ENVIRONMENT}"

	log warning "Terraform root: ${terraform_root_dir}"
	log warning "Configuring GCS backend: ${BUCKET_NAME}/${backend_prefix}"
	write_backend_configuration "${terraform_backend_file}" "${backend_prefix}"
	write_variable_values \
		"${terraform_variables_file}" "${terraform_project_id}" "${terraform_location}" "${deployment}"
}

# Terraform 設定ファイル生成処理を実行する。
main() {
	local deployment

	parse_common_args "terraform-configure" "$@"
	if [[ "${HELP_REQUESTED}" == "true" ]]; then
		usage
		return 0
	fi

	load_env_file
	validate_inputs
	derive_values
	verify_terraform_roots
	verify_tool_versions
	verify_authentication_and_project
	print_execution_context

	if ! has_state_bucket; then
		die "State bucket was not found in project ${PROJECT_ID_RAW_DATA}: ${BUCKET_URL}"
	fi
	verify_bucket_configuration || die "State bucket configuration does not match bootstrap."

	for deployment in "${DEPLOYMENTS[@]}"; do
		configure_deployment "${deployment}"
	done
	log success "Result: Terraform configuration completed"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
	main "$@"
fi
