#!/usr/bin/env bash
#
# env ファイルから対象環境の Terraform backend と tfvars ファイルを生成する。
#
# Requirement Bash Version
#   GNU Bash 4.4 or later
#
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
PROJECT_ROOT_DIR="$(cd -- "${SCRIPT_DIR}/../.." >/dev/null 2>&1 && pwd -P)"

# env ファイルの値から自動生成される値
TERRAFORM_ROOT_DIR=""
TERRAFORM_BACKEND_FILE=""
TERRAFORM_VARIABLES_FILE=""

GENERATED_FILE_HEADER="# Generated by scripts/terraform-configure.sh. Do not edit."

# shellcheck source-path=SCRIPTDIR
# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"

# 使用方法を表示する。
usage() {
	cat <<'USAGE'
Usage:
  terraform-configure.sh --env-file ENV_FILE

Required option:
  --env-file ENV_FILE  Project IDs, locations, ENVIRONMENT, and SUFFIX input file

Other option:
  -h, --help            Show this help

Example:
  ./scripts/terraform-configure.sh --env-file config/dev.env.local

Exit status:
  0  Terraform configuration completed
  1  Authentication or Google Cloud operation failed
  2  Invalid command-line option or input
USAGE
}

# 指定した一時ファイルを実際の管理対象ファイルとして配置する。
move_generated_file() {
	local temporary_file="$1"
	local target_file="$2"
	local description="$3"

	# 既存ファイルが同一ファイルであった場合スキップ。
	if [[ -f "${target_file}" ]] && cmp -s -- "${temporary_file}" "${target_file}"; then
		rm -f -- "${temporary_file}"
		log success "${description}: already current"
		return 0
	fi

	# mktemp で作成されている一時ファイルのパーミッションを変更する。
	if ! chmod 0644 "${temporary_file}"; then
		rm -f -- "${temporary_file}"
		die "Failed to set generated file permissions: ${target_file}"
	fi

	# 一時ファイルを実際のファイルパスに移動する。
	if ! mv -f -- "${temporary_file}" "${target_file}"; then
		rm -f -- "${temporary_file}"
		die "Failed to move generated file: ${target_file}"
	fi
	log success "${description}: written to ${target_file}"
}

# Terraform Backend ファイルを生成する。
write_backend_configuration() {
	local temporary_file

	temporary_file="$(mktemp "${TERRAFORM_BACKEND_FILE}.XXXXXX")" \
		|| die "Failed to create a temporary backend file."

	if ! printf '%s\n' \
		"${GENERATED_FILE_HEADER}" \
		'terraform {' \
		'  backend "gcs" {' \
		"    bucket = \"${BUCKET_NAME}\"" \
		"    prefix = \"${BACKEND_PREFIX}\"" \
		'  }' \
		'}' >"${temporary_file}"; then
		rm -f -- "${temporary_file}"
		die "Failed to write the Terraform backend configuration."
	fi

	move_generated_file "${temporary_file}" "${TERRAFORM_BACKEND_FILE}" "Terraform backend"
}

# Terraform tfvars ファイルを生成する。
write_variable_values() {
	local temporary_file

	temporary_file="$(mktemp "${TERRAFORM_VARIABLES_FILE}.XXXXXX")" \
		|| die "Failed to create a temporary variable file."

	if ! printf '%s\n' \
		"${GENERATED_FILE_HEADER}" \
		"project_id_raw_data  = \"${PROJECT_ID_RAW_DATA}\"" \
		"project_id_mart_red  = \"${PROJECT_ID_MART_RED}\"" \
		"project_id_mart_blue = \"${PROJECT_ID_MART_BLUE}\"" \
		"location_raw_data    = \"${LOCATION_RAW_DATA,,}\"" \
		"location_mart_red    = \"${LOCATION_MART_RED,,}\"" \
		"location_mart_blue   = \"${LOCATION_MART_BLUE,,}\"" \
		"environment          = \"${ENVIRONMENT}\"" \
		"suffix               = \"${SUFFIX}\"" >"${temporary_file}"; then
		rm -f -- "${temporary_file}"
		die "Failed to write the Terraform variable values."
	fi

	move_generated_file "${temporary_file}" "${TERRAFORM_VARIABLES_FILE}" "Terraform variables"
}

# Terraform 設定ファイルの作成パスを設定する。
derive_terraform_paths() {
	TERRAFORM_ROOT_DIR="${PROJECT_ROOT_DIR}/terraform/environments/${ENVIRONMENT}"
	TERRAFORM_BACKEND_FILE="${TERRAFORM_ROOT_DIR}/terraform-backend.tf"
	TERRAFORM_VARIABLES_FILE="${TERRAFORM_ROOT_DIR}/terraform.auto.tfvars"
}

# Terraform 設定ファイル生成処理を実行する。
main() {
	parse_common_args "terraform-configure" "$@"
	if [[ "${HELP_REQUESTED}" == "true" ]]; then
		usage
		return 0
	fi

	load_env_file
	validate_inputs
	derive_values
	derive_terraform_paths
	verify_tool_versions
	verify_authentication_and_project
	print_execution_context

	[[ -d "${TERRAFORM_ROOT_DIR}" ]] || die "Terraform root was not found: ${TERRAFORM_ROOT_DIR}"

	if ! has_state_bucket; then
		die "State bucket was not found in project ${PROJECT_ID_RAW_DATA}: ${BUCKET_URL}"
	fi
	verify_bucket_configuration || die "State bucket configuration does not match bootstrap."

	log warning "Terraform root: ${TERRAFORM_ROOT_DIR}"
	log warning "Configuring GCS backend: ${BUCKET_NAME}/${BACKEND_PREFIX}"
	write_backend_configuration
	write_variable_values
	log success "Result: Terraform configuration completed"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
	main "$@"
fi
