# Generated by scripts/terraform-configure.sh. Do not edit.
project_id_raw_data  = "kawata-atsushi"
project_id_mart_red  = "kawata-atsushi"
project_id_mart_blue = "kawata-atsushi"
location_raw_data    = "asia-northeast1"
location_mart_red    = "asia-northeast1"
location_mart_blue   = "asia-northeast1"
environment          = "dev"
suffix               = "sample"
